### ISSUE TITLE
Prepare first release

### ISSUE THREAD

**Issue by koxudaxi** [strawberry-graphql/strawberry-pycharm-plugin#2]
###  plugin.xml
- [ ] change Email
- [ ] add description

### .github/workflows/publish.yml
- [ ] set `pluginId` of `Publish a plugin` section. 
https://plugins.jetbrains.com/docs/marketplace/plugin-upload.html

### Secrets
- [ ] add `GITHUB_TOKEN` for creating GitHub-release

## Related PRs
https://github.com/strawberry-graphql/strawberry-pycharm-plugin/pull/1

**Comment by koxudaxi** [comment]
@patrick91 
I have created a to-do list to release the plugin.
Would you please check it?

**Comment by patrick91** [comment]
This has been done, we are waiting for approval from jetbrains 😊
